#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  output:
    ansi:
      enabled: detect
  sql:
    init:
      platform: postgresql
      mode: always
      continue-on-error: true


  datasource:
    url: jdbc:postgresql://localhost:5432/DirtyShop
    username: postgres
    password: root

  # Jackson Serialization Issue Resolver
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
    cache-names: users,restaurants
    caffeine.spec: maximumSize=1,expireAfterAccess=60s

logging:
  level:
    root: WARN
    com.avr.restaurant: DEBUG
    com.avr.restaurant.web.GlobalExceptionHandler: ERROR
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
  file:
    name: logs/application-debug.log
server:
  error:
    include-message: always

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true